---
title: "Data for Kristen's students"
author: "Dylan Titmuss"
date: "`r Sys.Date()`"
output: html_document
editor_options: 
  chunk_output_type: console
---

## Load packages
```{r}
library(tidyverse)
library(readxl)
library(janitor)
```

## Load datasheet to fill
```{r}
#blank <- read_csv("~/Downloads/PHAB LAB Blood samples(Genetic Sex for Size Morphology).csv")
blank <- read_csv("~/Downloads/Size Morphology Study(Tylers Dataset).csv") %>%
  remove_empty("rows")

morph <- read_xlsx("~/Desktop/Repos/GullsOfAppledore/data/reference_sheets_and_qrys/All_Captures_and_Recaptures_grouped_(w_morph).xlsx") %>%
  mutate(age = case_when(age == "Adult" ~ "adult",
                         age == "Chick" ~ "chick",
                         .default = age))

### ***need to go and get 2025 morph data; re-run

morph2025chicks <- read_xlsx("~/Desktop/Repos/GullsOfAppledore/data/2025_GBBGchicks-banded.xlsx")
```

## Check Fed/field match-ups & fill in missing PFRs
```{r}
check <- blank %>%
  mutate(databaseID = NA)

for(i in 1:nrow(check)) {
  feds <- na.omit(morph$BirdID[morph$USGS == check$Government.ID[i]])
  fields <- na.omit(morph$BirdID[morph$`Field Readable` == check$Field.Readable.ID[i]])
  ids <- unique(c(feds, fields))
  check$databaseID[i] <- ifelse(length(ids) > 0, list(ids), NA) %>%
    as.character()
}

check$fed <- NA
check$field <- NA

for(i in 1:nrow(check)) {
  feds <- unique(na.omit(morph$USGS[morph$BirdID == check$databaseID[i]]))
  check$fed[i] <- ifelse(length(feds) > 0, list(feds), NA) %>%
    as.character()
  fields <- unique(na.omit(morph$`Field Readable`[morph$BirdID == check$databaseID[i]]))
  check$field[i] <- ifelse(length(fields) > 0, list(fields), NA) %>%
    as.character()
}

check <- check %>%
  mutate(fed_check = Government.ID == fed,
         field_check = Field.Readable.ID == field)

# fill in missing PFRs
for(i in 1:nrow(check)) {
  if(is.na(check$Field.Readable.ID[i])) {
    fields <- unique(na.omit(morph$`Field Readable`[morph$BirdID == check$databaseID[i]]))
    if(length(fields) > 1) {
      print(check$Government.ID[i])
    }
    check$Field.Readable.ID[i] <- ifelse(length(fields) > 0, fields, NA)
  }
}
```

## Match data
```{r}
# initialize columns
check$Age.Captured <- NA
check$Year.Captured <- NA
check$Head.Size <- NA
check$Tarsus.Length <- NA
check$Mass <- NA

for(i in 1:nrow(check)) {
  gullID <- check$databaseID[i]
  if(is.na(gullID)) {
    next
  }
  subset <- morph %>%
    filter(BirdID == gullID)
  if(nrow(subset) == 0) {
    print(paste("Not found:", check$Government.ID[i]))
    next
  }
  subset2 <- subset %>%
    filter(!is.na(head) | !is.na(tarsus) | !is.na(weight))
  if(nrow(subset2) > 0) {
    subset2 <- subset2 %>%
      group_by(Year, Month, Day) %>%
      summarise(age = unique(age),
                head = unique(head),
                tarsus = unique(tarsus),
                weight = unique(weight))
      # slice(1) %>%   # alternative method; assumes all entries on same date have same morphs
      # ungroup()
    check$Age.Captured[i] <- paste(subset2$age, collapse = ", ")
    check$Year.Captured[i] <- paste(subset2$Year, collapse = ", ")
    check$Head.Size[i] <- paste(round(subset2$head, 1), collapse = ", ")
    check$Tarsus.Length[i] <- paste(round(subset2$tarsus, 1), collapse = ", ")
    check$Mass[i] <- paste(round(subset2$weight, 1), collapse = ", ")
  }
  if(nrow(subset2) == 0) {
    subset <- subset %>%
      group_by(Year, Month, Day) %>%
      slice(1) %>%
      ungroup()
    check$Age.Captured[i] <- paste(subset$age, collapse = ", ")
    check$Year.Captured[i] <- paste(subset$Year, collapse = ", ")
    check$Head.Size[i] <- paste(subset$head, collapse = ", ")
    check$Tarsus.Length[i] <- paste(subset$head, collapse = ", ")
    check$Mass[i] <- paste(round(subset$weight, 1), collapse = ", ")
  }
}

check <- check %>%
  mutate(Age.Measured = case_when(Age.Measured == "Adult" ~ "adult",
                                  Age.Measured == "Chick" ~ "chick",
                                  .default = Age.Measured)) %>%
  select(-c(databaseID, fed_check, field_check)) %>%
  relocate(Year.Captured, .after = Age.Captured) %>%
  relocate(Mass, .after = Tarsus.Length)

## label 2025 chicks
check <- check %>%
  mutate(Year.Captured = case_when(check$Field.Readable.ID %in% morph2025chicks$Field_Band ~
                                     "2025",
                                   .default = Year.Captured),
         Age.Captured = case_when(check$Field.Readable.ID %in% morph2025chicks$Field_Band ~
                                     "chick",
                                   .default = Age.Captured))

write_csv(check, "~/Downloads/Size Morphology Study(Tylers Dataset)_2025-11-05.csv")
```

## Round 2
```{r}
part_blank <- read_csv("~/Downloads/PHAB-Lab-Genetic-Sex-for-Size-Morphology_with DYLAN.csv")

for(i in 1:nrow(part_blank)) {
  gullID <- part_blank$Government.ID[i]
  subset <- morph %>%
    filter(USGS == gullID)
  if(nrow(subset) == 0) {
    print(paste("Not found:", gullID))
    next
  }
  if(is.na(part_blank$Field.Readable.ID[i])) {
    part_blank$Field.Readable.ID[i] <- paste(unique(subset$`Field Readable`), collapse = ", ")
  }
  subset2 <- subset %>%
    filter(!is.na(head) | !is.na(tarsus))
  if(nrow(subset2) > 0) {
    part_blank$Age.Captured[i] <- paste(subset2$age, collapse = ", ")
    part_blank$Head.Size[i] <- paste(round(subset2$head, 1), collapse = ", ")
    part_blank$Tarsus.Length[i] <- paste(round(subset2$tarsus, 1), collapse = ", ")
  }
  if(nrow(subset2) == 0) {
    part_blank$Age.Captured[i] <- paste(subset$age, collapse = ", ")
    part_blank$Head.Size[i] <- paste(subset$head, collapse = ", ")
    part_blank$Tarsus.Length[i] <- paste(subset$head, collapse = ", ")
  }
}

part_blank$Notes[is.na(part_blank$Notes)] <- ""

write_csv(part_blank, "~/Downloads/PHAB-Lab-Genetic-Sex-for-Size-Morphology_2025-03-04.csv")
```
